language: node_js
node_js: stable
script:
  - "npm run test-travis"
after_script:
  - "npm install coveralls@3 && cat coverage/lcov.info | coveralls"
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
