language: node_js
node_js: stable
after_success:
  - c8 report --reporter=text-lcov | coveralls
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
